# ---
# jupyter:
#   jupytext:
#     text_representation:
#       extension: .py
#       format_name: percent
#       format_version: '1.3'
#       jupytext_version: 1.19.3
#   kernelspec:
#     display_name: Python 3
#     language: python
#     name: python3
# ---

# %% [markdown]
# # EVE Analysis: ViroSync Results
#
# Publication-quality visualizations of endogenous viral elements (EVEs)
# detected by ViroSync, with flanking region context, taxonomy-colored genes,
# and structural markers.
#
# This notebook is auto-generated by ViroSync and can also be run manually.
# To run by hand, set `RESULTS_DIR` to a ViroSync output directory and
# `TAX_LABELS_PATH` to the taxonomy `labels.tsv` used for that run.

# %% tags=["parameters"]
# Parameters (injected by papermill at runtime, or set manually)
RESULTS_DIR = "."
GENOME_ID = ""  # auto-detected from EVE IDs if empty
TAX_LABELS_PATH = ""
SHOW_TIERS = ["HIGH", "MEDIUM", "LOW"]
ANI_THRESHOLD = 90.0
FLANK_SIZE = 5000

# %%
import subprocess
import tempfile
import pandas as pd
import numpy as np
from IPython import get_ipython

_ipython = get_ipython()
if _ipython is not None:
    _ipython.run_line_magic('matplotlib', 'inline')

import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from matplotlib.lines import Line2D
import json
from collections import Counter, defaultdict

# %%
# Keep these helpers self-contained: papermill executes this notebook from the
# result directory, where the ViroSync source package may not be importable.
import hashlib
import re
from pathlib import Path
from urllib.parse import quote

_PORTABLE_FILENAME_COMPONENT = re.compile(r"[A-Za-z0-9._-]+\Z")
_MAX_FILENAME_COMPONENT_LENGTH = 180
_REPORT_NCLDV_MCP_MODELS = frozenset({
    "og1352",
    "og484",
    "vs000086",
    "vs000309",
    "gamadvirusmcp",
    "gvogm0003",
})
_REPORT_MCP_HMM_PREFIXES = (
    "gamadvirusmcp",
    "mcp_mirus",
    "mcp_poli",
    "mirus_mcp",
    "plv_mcp",
    "vp_mcp",
)
_REPORT_MCP_HMM_EXACT = _REPORT_NCLDV_MCP_MODELS | frozenset({"mcp"})
_REPORT_MCP_WORD_CHARS_ONLY = re.compile(r"^[a-z0-9_]*$")


def _report_is_mcp_gene(name):
    """Mirror the pipeline MCP detector while keeping this notebook portable."""
    if not name:
        return False
    lower = str(name).lower().strip()
    if not lower:
        return False
    if lower in _REPORT_MCP_HMM_EXACT:
        return True
    for prefix in _REPORT_MCP_HMM_PREFIXES:
        if lower.startswith(prefix):
            suffix = lower[len(prefix):]
            if _REPORT_MCP_WORD_CHARS_ONLY.match(suffix):
                return True
    return False


def _csv_values(value):
    if value is None or (not isinstance(value, (list, tuple)) and pd.isna(value)):
        return []
    if isinstance(value, (list, tuple)):
        return [str(item) for item in value]
    return [item for item in str(value).split(',') if item]


def _report_resolve_taxonomy_target(target, taxonomy_lookup):
    """Mirror the pipeline target resolver while keeping this notebook portable."""
    org_id = str(target or '').split('|', 1)[0]
    if not taxonomy_lookup or org_id in taxonomy_lookup:
        return org_id

    candidates = [org_id]
    legacy_prefix = 'PHAGE__VARDNA__'
    if org_id.startswith(legacy_prefix):
        candidates.append('PHAGE__' + org_id.removeprefix(legacy_prefix))

    for base in candidates:
        if base in taxonomy_lookup:
            return base
        if '__' not in base:
            continue
        prefix, suffix = base.split('__', 1)
        parts = suffix.split('_')
        for index in range(len(parts) - 1, 0, -1):
            candidate = prefix + '__' + '_'.join(parts[:index])
            if candidate in taxonomy_lookup:
                return candidate
    return org_id


def _report_target_lineage(target, taxonomy_lookup):
    org_id = _report_resolve_taxonomy_target(target, taxonomy_lookup)
    return taxonomy_lookup.get(org_id, '')


def _report_canonical_viral_category(prefix, target, taxonomy_lookup):
    """Normalize current and legacy viral taxonomy labels for display."""
    prefix = str(prefix or '').rstrip('_').upper()
    if prefix in {'PPV', 'PLV', 'VP', 'VP_PLV'}:
        return 'PPV'
    if prefix == 'PHAGE':
        lineage_tokens = {
            token.strip().lower()
            for token in _report_target_lineage(target, taxonomy_lookup).split('|')
            if token.strip()
        }
        return 'PPV' if 'preplasmiviricota' in lineage_tokens else 'PHAGE'
    if prefix in {'NCLDV', 'MIRUS', 'CRESS', 'GVMAG'}:
        return prefix
    return None


def safe_ratio(numerator, denominator):
    """Return a finite zero when a report denominator is empty or zero."""
    return numerator / denominator if denominator else 0.0


def safe_filename_component(value):
    if not isinstance(value, str):
        raise TypeError("filename component must be a string")
    encoded_bytes = value.encode("utf-8", errors="surrogatepass")
    if (
        value
        and value not in {".", ".."}
        and _PORTABLE_FILENAME_COMPONENT.fullmatch(value) is not None
        and len(encoded_bytes) <= _MAX_FILENAME_COMPONENT_LENGTH
    ):
        return value
    encoded = quote(value, safe="._-", errors="surrogatepass").replace("~", "%7E")
    digest = hashlib.sha256(encoded_bytes).hexdigest()[:16]
    prefix_limit = _MAX_FILENAME_COMPONENT_LENGTH - len(digest) - 3
    encoded = encoded[:prefix_limit] or "empty"
    return f"%{encoded}--{digest}"


def safe_filename_components(values, label="identifier"):
    raw_values = list(values)
    indices_by_value = {}
    for index, value in enumerate(raw_values):
        indices_by_value.setdefault(value, []).append(index)
    duplicates = {
        value: indices
        for value, indices in indices_by_value.items()
        if len(indices) > 1
    }
    if duplicates:
        details = "; ".join(
            f"{value!r} at indices {', '.join(str(index) for index in indices)}"
            for value, indices in sorted(duplicates.items())
        )
        raise ValueError(f"duplicate {label}s: {details}")
    components = {}
    raw_value_by_component = {}
    for value in raw_values:
        component = safe_filename_component(value)
        conflicting_value = raw_value_by_component.get(component)
        if conflicting_value is not None:
            raise ValueError(
                f"{label} filename encoding collision: "
                f"{conflicting_value!r} and {value!r}"
            )
        components[value] = component
        raw_value_by_component[component] = value
    return components


def require_strict_child(root, candidate):
    resolved_root = Path(root).resolve(strict=False)
    resolved_candidate = Path(candidate).resolve(strict=False)
    if (
        resolved_candidate == resolved_root
        or resolved_root not in resolved_candidate.parents
    ):
        raise ValueError(
            f"path must be a strict child of {resolved_root}: {resolved_candidate}"
        )
    return resolved_candidate


# %%
# --- Style setup (beautiful-data-viz) ---
def set_beautiful_style():
    plt.rcParams.update({
        'font.family': 'sans-serif',
        'font.sans-serif': ['Helvetica', 'Arial', 'DejaVu Sans'],
        'font.size': 10,
        'axes.titlesize': 13,
        'axes.labelsize': 11,
        'xtick.labelsize': 9,
        'ytick.labelsize': 8,
        'legend.fontsize': 8,
        'figure.dpi': 150,
        'savefig.dpi': 300,
        'axes.spines.top': False,
        'axes.spines.right': False,
        'axes.linewidth': 0.8,
        'xtick.major.width': 0.8,
        'ytick.major.width': 0.8,
        'axes.grid': False,
        'figure.facecolor': 'white',
        'axes.facecolor': 'white',
        'savefig.bbox': 'tight',
        'savefig.facecolor': 'white',
    })

def finalize_axes(ax, despine_left=False):
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)
    if despine_left:
        ax.spines['left'].set_visible(False)

set_beautiful_style()

# --- Paths ---
BASE = Path(RESULTS_DIR)
SYNTHESIS = BASE / 'phase3_synthesis'
if not (SYNTHESIS / 'evidence_profiles.json').exists():
    SYNTHESIS = BASE
TAX_LABELS_PATH = Path(TAX_LABELS_PATH) if TAX_LABELS_PATH else None

# --- Taxonomy labels ---
tax_labels = {}
if TAX_LABELS_PATH is not None and TAX_LABELS_PATH.is_file():
    with open(TAX_LABELS_PATH) as f:
        for line in f:
            parts = line.rstrip('\n').split('\t')
            if len(parts) >= 2:
                tax_labels[parts[0]] = parts[1]
    print(f'Loaded {len(tax_labels):,} taxonomy labels')
else:
    print("Taxonomy labels were not configured -- host detection will be limited")

# --- Resolve taxonomy and infer the dominant host lineage for display ---
_host_model_path = BASE / 'phase1' / 'marker_validation' / 'host_signature_model.json'
_boundary_taxonomy_path = BASE / 'phase2' / 'boundary_diamond' / 'taxonomy_map.tsv'
_boundary_taxonomy = (
    pd.read_csv(_boundary_taxonomy_path, sep='\t', engine='python')
    if _boundary_taxonomy_path.exists()
    else pd.DataFrame()
)
BOUNDARY_TAXONOMY = (
    _boundary_taxonomy.set_index('porf_id', drop=False).to_dict('index')
    if not _boundary_taxonomy.empty
    else {}
)


def _resolve_taxonomy_target(target):
    return _report_resolve_taxonomy_target(target, tax_labels)


def _target_lineage(target):
    return _report_target_lineage(target, tax_labels)


HOST_GENUS = ''
HOST_TAXA = set()
_LINEAGE_LEVELS = ['Domain', 'Supergroup', 'Order', 'Suborder', 'Family', 'Genus', 'Species']
if _host_model_path.exists() and tax_labels:
    with open(_host_model_path) as _f:
        _host_weights = json.load(_f).get('token_weights', {})
    _tok_level = {}
    for _lineage in tax_labels.values():
        for _i, _level in enumerate(_lineage.split('|')):
            _token = _level.strip().lower()
            if _token in _host_weights and _i < _tok_level.get(_token, 99):
                _tok_level[_token] = _i
    _by_level = defaultdict(list)
    for _token, _level_index in _tok_level.items():
        _by_level[_level_index].append(_token)
    for _level_index in sorted(_by_level):
        if _level_index == 0:
            continue
        _best = max(
            _by_level[_level_index],
            key=lambda token: _host_weights.get(token, 0.0),
        )
        HOST_TAXA.add(_best)
        if _level_index == 5:
            HOST_GENUS = _best
print(f'Host genus: {HOST_GENUS!r}  Host lineage taxa: {sorted(HOST_TAXA)}')


def is_host_gene(target):
    """Return whether a best-hit lineage overlaps the run's dominant host lineage."""
    lineage_tokens = {
        token.strip().lower()
        for token in _target_lineage(target).split('|')
        if token.strip()
    }
    return bool(lineage_tokens & HOST_TAXA)


def _canonical_viral_category(prefix, target):
    return _report_canonical_viral_category(prefix, target, tax_labels)


def _marker_viral_category(taxonomy_record):
    """Use the highest-ranked identity-qualified viral hit for a validated marker."""
    if not taxonomy_record:
        return None
    prefixes = _csv_values(taxonomy_record.get('top10_prefixes'))
    targets = _csv_values(taxonomy_record.get('top10_targets'))
    pidents = _csv_values(taxonomy_record.get('top10_pidents'))
    for index, prefix in enumerate(prefixes):
        try:
            pident = float(pidents[index])
        except (IndexError, TypeError, ValueError):
            continue
        target = targets[index] if index < len(targets) else ''
        category = _canonical_viral_category(prefix, target)
        if category and pident >= 25.0:
            return category
    return None

# --- Colorblind-safe palette (Tol bright) ---
COLORS = {
    'PPV':       '#EE7733',
    'PLV':       '#EE7733',
    'VP':        '#AA3377',
    'CRESS':     '#CCBB44',
    'MIRUS':     '#882255',
    'NCLDV':     '#009988',
    'GVMAG':     '#332288',
    'HOST':      '#0077BB',
    'EUK_HOST':  '#0077BB',
    'EUK':       '#33BBEE',
    'EUK_OTHER': '#33BBEE',
    'BAC':       '#CC3311',
    'ARC':       '#AA4499',
    'PHAGE':     '#FF7F00',
    'UNKNOWN':   '#BBBBBB',
}

TIER_COLORS = {'HIGH': '#333333', 'MEDIUM': '#777777', 'LOW': '#BBBBBB'}

print('Setup complete.')

# %%
# ---- Load data ----

# 1. Evidence profiles
with open(SYNTHESIS / 'evidence_profiles.json') as f:
    all_profiles = json.load(f)

# Auto-detect genome prefix from first EVE ID
if all_profiles:
    _first_eve = list(all_profiles.keys())[0]  # e.g. 'EVE_stena|contig_120_27714-42015'
    EVE_PREFIX = _first_eve.split('|')[0]       # 'EVE_stena'
    if not GENOME_ID:
        GENOME_ID = EVE_PREFIX.replace('EVE_', '')
else:
    EVE_PREFIX = 'EVE'
    if not GENOME_ID:
        GENOME_ID = 'unknown'

# FILTER: keep only selected confidence tiers
profiles = {k: v for k, v in all_profiles.items()
            if v.get('confidence_tier', '') in SHOW_TIERS}
print(f'Evidence profiles: {len(all_profiles)} total, {len(profiles)} after filtering to {SHOW_TIERS}')

if not profiles:
    print(f'\nNo EVEs detected at tiers {SHOW_TIERS}. Nothing to plot.')

# 2. Gene taxonomy (core + flanking in one file)
gene_tax_path = SYNTHESIS / 'gene_taxonomy' / 'gene_taxonomy_all.tsv'
if gene_tax_path.exists() and profiles:
    gene_tax = pd.read_csv(gene_tax_path, sep='\t', engine='python')
    gene_tax = gene_tax[gene_tax['eve_id'].isin(profiles.keys())].copy()
    core_genes = gene_tax[gene_tax['is_flanking'] == 0].copy()
    flanking_genes = gene_tax[gene_tax['is_flanking'] == 1].copy()
    print(f'Genes: {len(gene_tax)} total ({len(core_genes)} core, {len(flanking_genes)} flanking)')
else:
    gene_tax = pd.DataFrame()
    core_genes = pd.DataFrame()
    flanking_genes = pd.DataFrame()

# 2b. Complete Prodigal gene coordinates and strands
porf_strands = {}
proteome_genes_by_scaffold = defaultdict(list)
_proteome_path = BASE / 'phase0' / 'proteome.fasta'
if _proteome_path.exists():
    with open(_proteome_path) as f:
        for line in f:
            if not line.startswith('>'):
                continue
            header = line[1:].rstrip('\n')
            parts = header.split(' # ')
            if len(parts) < 4:
                continue
            porf_id = parts[0].strip().split()[0]
            try:
                start = int(parts[1]) - 1
                end = int(parts[2])
            except ValueError:
                continue
            strand = {'1': '+', '-1': '-'}.get(parts[3].strip())
            id_match = re.search(r'ID=([^;]+)', header)
            gene_index = (
                id_match.group(1).rsplit('_', 1)[-1]
                if id_match
                else porf_id.rsplit('_', 1)[-1]
            )
            scaffold = (
                porf_id[:-(len(gene_index) + 1)]
                if gene_index and porf_id.endswith(f'_{gene_index}')
                else porf_id.rsplit('_', 1)[0]
            )
            porf_strands[porf_id] = strand or '.'
            proteome_genes_by_scaffold[scaffold].append({
                'porf_id': porf_id,
                'start': start,
                'end': end,
                'strand': strand or '.',
            })
for scaffold_genes in proteome_genes_by_scaffold.values():
    scaffold_genes.sort(key=lambda gene: (gene['start'], gene['end'], gene['porf_id']))
print(
    f'Prodigal genes: {len(porf_strands):,} across '
    f'{len(proteome_genes_by_scaffold):,} scaffolds'
)

# 3. Jelly roll capsid proteins -> porf_id map
jelly_roll_map = {}
jr_path = SYNTHESIS / 'virosync_jelly_roll_proteins.tsv'
if jr_path.exists():
    with open(jr_path) as f:
        next(f)  # skip header
        for line in f:
            line = line.strip()
            if not line:
                continue
            cols = line.split('\t')
            protein_id = cols[0]
            m = re.match(r'^(.+)\|aa\d+-\d+$', protein_id)
            porf_id = m.group(1) if m else protein_id
            jelly_roll_map[porf_id] = {
                'type': cols[1] if len(cols) > 1 else '',
                'confidence': float(cols[2]) if len(cols) > 2 else 0,
            }
print(f'Jelly roll proteins: {len(jelly_roll_map)}')

# 3b. MCP (major capsid protein) marker genes -> porf_id set.
# Sourced from validated HMM marker hits (e.g. plv_MCP_* and vp_MCP_*), so MCP
# genes are highlighted even when structural jelly-roll detection is off.
mcp_porf_ids = set()
_mh_path = BASE / 'phase1' / 'marker_validation' / 'validated_marker_hits.tsv'
if _mh_path.exists():
    with open(_mh_path) as f:
        _hdr = f.readline().rstrip('\n').split('\t')
        try:
            _qi = _hdr.index('query_porf')
            _ti = _hdr.index('hmm_target')
            _vi = _hdr.index('validation_status')
        except ValueError:
            _qi, _ti, _vi = 0, 5, 7
        for line in f:
            cols = line.rstrip('\n').split('\t')
            if len(cols) <= max(_qi, _ti, _vi):
                continue
            if _report_is_mcp_gene(cols[_ti]) and cols[_vi] == 'validated':
                _m = re.match(r'^(.+)\|aa\d+-\d+$', cols[_qi])
                mcp_porf_ids.add(_m.group(1) if _m else cols[_qi])
print(f'MCP marker genes: {len(mcp_porf_ids)}')

# 4. RT genes from InterProScan PF00078
rt_gene_ids = set()
ipr_path = BASE / 'phase3' / 'interproscan' / 'interproscan_batch.tsv'
if ipr_path.exists():
    with open(ipr_path) as f:
        for line in f:
            cols = line.rstrip('\n').split('\t')
            if len(cols) >= 5 and cols[4] == 'PF00078':
                pipe_parts = cols[0].split('|')
                porf_id = pipe_parts[-2] + '|' + pipe_parts[-1]
                rt_gene_ids.add(porf_id)
print(f'RT genes (PF00078): {len(rt_gene_ids)}')

# 5. Predictions detailed
predictions = pd.DataFrame()
_det_path = SYNTHESIS / 'virosync_predictions_detailed.tsv'
if _det_path.exists() and profiles:
    predictions = pd.read_csv(_det_path, sep='\t', engine='python')
    predictions = predictions[predictions['eve_id'].isin(profiles)].copy()
print(f'Predictions: {len(predictions)}')

# %% [markdown]
# ## Host Signature Model
#
# ViroSync builds a host signature model from **COG** and **BUSCO** marker genes found in the genome's predicted proteome. These are universal cellular genes (ribosomal proteins, metabolic enzymes) that indicate host origin. Each COG/BUSCO gene is searched against a Diamond database, and the top-10 hits' taxonomy lineages are aggregated into a weighted token model (`weight_mode=rank`: best hit = 10, rank 2 = 9, ..., rank 10 = 1; bitscores are not used).
#
# The resulting model captures the host's taxonomic identity at every level, from domain down to species. It is used in Phase 2 boundary refinement to distinguish host genes from viral insertions. Tokens from distant taxa (e.g. SAR, Fungi) appear because COG/BUSCO genes are universal and some Diamond top-10 hits come from organisms outside the host lineage. Percent labels in the plot report each token's weight relative to the largest model weight; `n` is the number of token occurrences, not a sample percentage.

# %%
# ---- Host Signature Model Summary ----

# 1. Load the host signature model
_model_path = BASE / 'phase1' / 'marker_validation' / 'host_signature_model.json'
_hits_path = BASE / 'phase1' / 'marker_validation' / 'validated_marker_hits.tsv'

if _model_path.exists():
    with open(_model_path) as f:
        _host_model = json.load(f)

    _token_weights = _host_model.get('token_weights', {})
    _token_counts = _host_model.get('token_counts', {})
    _host_prefixes = _host_model.get('host_prefixes', [])
    _weight_mode = _host_model.get('weight_mode', 'rank')
else:
    _host_model = None
    print('Host signature model not found (phase1/marker_validation/host_signature_model.json)')

# 2. Load marker hits and classify COG vs BUSCO
if _hits_path.exists():
    _hits_df = pd.read_csv(_hits_path, sep='\t', engine='python')
    _is_cog = _hits_df['hmm_target'].str.startswith('COG')
    _is_busco = _hits_df['hmm_target'].str.contains('at2759')
    _host_hits = _hits_df[_is_cog | _is_busco].copy()

    _n_cog = _is_cog.sum()
    _n_busco = _is_busco.sum()
    _cog_unique = _hits_df.loc[_is_cog, 'hmm_target'].nunique()
    _busco_unique = _hits_df.loc[_is_busco, 'hmm_target'].nunique()
    _total_markers = len(_hits_df)
else:
    _host_hits = pd.DataFrame()

# 3. Assign each model token to its taxonomy level
_LEVEL_NAMES = ['Domain', 'Supergroup', 'Order', 'Suborder', 'Family', 'Genus', 'Species']
_TOP_N = 5

_level_tokens = defaultdict(list)
if _host_model and tax_labels:
    _token_to_levels = defaultdict(set)
    for _key, _lineage in tax_labels.items():
        _levels = _lineage.split('|')
        for _i, _level in enumerate(_levels):
            _level_lower = _level.strip().lower()
            if _level_lower in _token_weights:
                _token_to_levels[_level_lower].add(_i)

    for _token, _levels_set in _token_to_levels.items():
        _primary = min(_levels_set)
        _level_tokens[_primary].append(
            (_token, _token_weights[_token], _token_counts.get(_token, 0)))

    for _i in range(len(_LEVEL_NAMES)):
        _level_tokens[_i] = sorted(_level_tokens.get(_i, []), key=lambda x: -x[1])

    # Inject EUK at Domain level. Domain tokens are excluded from scoring, but
    # the model's host prefixes and marker count still document the source.
    if 'EUK__' in _host_prefixes and not any(t[0] == 'EUK' for t in _level_tokens.get(0, [])):
        _euk_hits = len(_host_hits)
        _level_tokens[0].insert(0, ('EUK', _host_model.get('max_weight', 0), _euk_hits))

# 4. Print summary
if _host_model:
    _max_w = _host_model.get('max_weight', 1.0) or 1.0
    print('Host Signature Model')
    print(f'  Prefixes:        {", ".join(_host_prefixes)}')
    print(f'  Weight mode:     {_weight_mode}', end='')
    if _weight_mode == 'rank':
        print('  (hit weights: rank1=10, rank2=9, ..., rank10=1)')
    else:
        print('  (hit weights: bitscore)')
    print(f'  Tokens:          {len(_token_weights)}')
    print()

    # Per-level breakdown
    for _i, _name in enumerate(_LEVEL_NAMES):
        _tokens = _level_tokens.get(_i, [])[:_TOP_N]
        if not _tokens:
            print(f'  {_name:<12s}  --')
            continue
        _best = _tokens[0]
        print(
            f'  {_name:<12s}  {_best[0]:<30s}  '
            f'{safe_ratio(_best[1], _max_w)*100:>5.1f}% of max weight  '
            f'({int(_best[2])} token occurrences)',
            end='',
        )
        if len(_tokens) > 1:
            _others = ', '.join(
                f'{t[0]} ({safe_ratio(t[1], _max_w)*100:.0f}% of max)'
                for t in _tokens[1:3]
            )
            print(f'   next: {_others}', end='')
        print()

    if not _host_hits.empty:
        print(f'\n  Based on {_n_cog + _n_busco} host marker hits '
              f'({_cog_unique} COGs, {_busco_unique} BUSCOs) '
              f'out of {_total_markers:,} total HMM hits '
              f'({safe_ratio(_n_cog + _n_busco, _total_markers):.1%})')

# 5. Figure: per-level taxonomy breakdown + COG/BUSCO panel
if _host_model and _level_tokens:
    _n_levels = len(_LEVEL_NAMES)
    _max_w = _host_model.get('max_weight', 1.0) or 1.0
    _has_markers = not _host_hits.empty

    if _has_markers:
        fig = plt.figure(figsize=(10, _n_levels * 1.1 + 1.5))
        gs = fig.add_gridspec(_n_levels, 2, width_ratios=[4, 1], hspace=0.55, wspace=0.35)
    else:
        fig = plt.figure(figsize=(8, _n_levels * 1.1 + 1.5))
        gs = fig.add_gridspec(_n_levels, 1, hspace=0.55)

    _cmap = plt.cm.YlOrRd

    for _i, _name in enumerate(_LEVEL_NAMES):
        ax = fig.add_subplot(gs[_i, 0])
        _tokens = _level_tokens.get(_i, [])[:_TOP_N]
        if not _tokens:
            ax.text(0.5, 0.5, 'no tokens', ha='center', va='center',
                    transform=ax.transAxes, color='#888888', fontsize=9)
            ax.set_ylabel(_name, fontsize=9, fontweight='bold', rotation=0,
                          ha='right', va='center', labelpad=65)
            ax.set_xlim(0, 1)
            for sp in ax.spines.values():
                sp.set_visible(False)
            ax.set_xticks([])
            ax.set_yticks([])
            continue

        _labels = [t[0].title() for t in _tokens]
        _weights = [t[1] for t in _tokens]
        _counts = [t[2] for t in _tokens]
        _colors = [_cmap(safe_ratio(w, _max_w)) for w in _weights]

        y_pos = np.arange(len(_labels))
        bars = ax.barh(y_pos, _weights, color=_colors, edgecolor='white',
                        linewidth=0.5, height=0.7)
        ax.set_yticks(y_pos)
        ax.set_yticklabels(_labels, fontsize=8)
        ax.set_xlim(0, _max_w * 1.18)
        ax.invert_yaxis()

        for bar, w, cnt in zip(bars, _weights, _counts):
            pct = safe_ratio(w, _max_w) * 100
            ax.text(bar.get_width() + _max_w * 0.01,
                    bar.get_y() + bar.get_height() / 2,
                    f'{pct:.0f}% max; n={int(cnt)}', va='center',
                    fontsize=7, color='#555555')

        ax.set_ylabel(_name, fontsize=9, fontweight='bold', rotation=0,
                      ha='right', va='center', labelpad=65)
        ax.spines['top'].set_visible(False)
        ax.spines['right'].set_visible(False)
        if _i < _n_levels - 1:
            ax.tick_params(axis='x', labelbottom=False)
            ax.set_xticklabels([])

    axes_list = [fig.axes[i] for i in range(len(fig.axes))]
    if axes_list:
        axes_list[-1].set_xlabel(
            'Cumulative token weight (% labels are relative to the model maximum)',
            fontsize=9,
        )

    # COG/BUSCO panel (right side, spanning middle rows)
    if _has_markers:
        ax_m = fig.add_subplot(gs[2:5, 1])
        _categories = ['COG', 'BUSCO']
        _hit_counts = [_n_cog, _n_busco]
        _unique_counts = [_cog_unique, _busco_unique]
        _bar_colors = ['#009988', '#EE7733']

        bars_m = ax_m.bar(_categories, _hit_counts, color=_bar_colors,
                          edgecolor='white', linewidth=0.8, width=0.55)
        for bar, total, unique in zip(bars_m, _hit_counts, _unique_counts):
            ax_m.text(bar.get_x() + bar.get_width() / 2,
                      bar.get_height() + max(_hit_counts) * 0.03,
                      f'{total:,}\n({unique})', ha='center', va='bottom',
                      fontsize=8, fontweight='bold')
        ax_m.set_ylabel('HMM hits')
        ax_m.set_title('Marker types', fontsize=9, fontweight='bold')
        ax_m.set_ylim(0, max(_hit_counts) * 1.3)
        ax_m.spines['top'].set_visible(False)
        ax_m.spines['right'].set_visible(False)

    fig.suptitle(f'{GENOME_ID} Host Signature: Taxonomy Token Weights',
                 fontsize=13, fontweight='bold')
    plt.savefig(BASE / 'host_signature_model.png', dpi=300, bbox_inches='tight')
    plt.show()

# %% [markdown]
# ## EVE Summary
#
# Counts and sizes of the canonical EVE predictions for this genome, drawn from one call set across two panels. Panel A stacks each confidence tier (HIGH, MEDIUM, LOW) by likely viral family and prints the tier total above each bar. Panel B shows the length distribution of each family as a box plot with the individual EVEs overlaid as points. Confidence tiers come from Phase 3 evidence scoring. In both panels a fixed family key colors PPV (Preplasmiviricota, covering Polinton-like viruses and virophages), NCLDV, Mirusviricota, and phage, and draws any other label, including MIXED and UNKNOWN, in gray.

# %%
# ---- EVE summary stats ----
status_counts = Counter(p['status'] for p in profiles.values())
tier_counts = Counter(p.get('confidence_tier', 'UNKNOWN') for p in profiles.values())
total_bp = sum(p['length'] for p in profiles.values())

print(f'Total canonical EVE predictions: {len(profiles)}')
print(f'Total EVE coverage:   {total_bp:,} bp ({total_bp/1e6:.2f} Mb)')
print()
print('Canonical tiers:')
for tier in ['HIGH', 'MEDIUM', 'LOW']:
    n = tier_counts.get(tier, 0)
    label = tier
    print(f'  {label:<12s} {n:>3d}')
print()
print('Family classification:')
def canon_family(value):
    """Fold legacy VP/PLV labels onto PPV so old and new runs group together."""
    token = str(value or 'UNKNOWN').strip().upper()
    return 'PPV' if token in ('VP', 'PLV') else token

all_families = Counter(canon_family(p.get('likely_family')) for p in profiles.values())
for fam, n in all_families.most_common():
    print(f'  {fam:<12s} {n:>3d}')

# Family classification colors (reused in later cells)
FAMILY_COLORS = {
    'PPV':     COLORS['PPV'],       # orange -- Preplasmiviricota (PLV + virophages)
    'NCLDV':   COLORS['NCLDV'],     # teal
    'MIRUS':   COLORS['MIRUS'],     # dark magenta
    'CRESS':   COLORS['CRESS'],     # yellow
    'PHAGE':   '#CC3311',           # red
    'PLV':     COLORS['PLV'],       # legacy label from pre-PPV result files
    'VP':      COLORS['VP'],        # legacy label from pre-PPV result files
    'UNKNOWN': COLORS['UNKNOWN'],   # gray
}
family_order = ['PPV', 'NCLDV', 'MIRUS', 'CRESS', 'PHAGE', 'PLV', 'VP', 'UNKNOWN']
tier_order = ['HIGH', 'MEDIUM', 'LOW']

tier_family_counts = {t: Counter() for t in tier_order}
for p in profiles.values():
    tier = p.get('confidence_tier', 'UNKNOWN')
    if tier not in tier_order:
        continue
    family = canon_family(p.get('likely_family'))
    if family not in FAMILY_COLORS:
        family = 'UNKNOWN'
    tier_family_counts[tier][family] += 1

# ---- Two-panel figure: classification + size distribution ----
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(8, 3.5))

# Panel A: stacked bar -- family composition per tier
x = np.arange(len(tier_order))
width = 0.55
bottoms = np.zeros(len(tier_order))

for family in family_order:
    vals = [tier_family_counts[t].get(family, 0) for t in tier_order]
    if sum(vals) == 0:
        continue
    ax1.bar(x, vals, width, bottom=bottoms, label=family,
            color=FAMILY_COLORS[family], edgecolor='white', linewidth=0.8)
    bottoms += np.array(vals, dtype=float)

for i, tier in enumerate(tier_order):
    total = sum(tier_family_counts[tier].values())
    ax1.text(i, bottoms[i] + 0.8, str(total), ha='center', va='bottom',
             fontsize=11, fontweight='bold')

ax1.set_xticks(x)
ax1.set_xticklabels(tier_order)
ax1.set_ylabel('Number of EVEs')
ax1.set_ylim(0, max(1.0, max(bottoms) * 1.18))
ax1.set_title('(A) Classification by Tier', fontweight='bold')
# Legend in the upper-left: the tallest (LOW) bar and its count label sit on
# the right, so 'upper left' avoids overlapping the data.
ax1.legend(fontsize=7, loc='upper left', framealpha=0.9)
finalize_axes(ax1)

# Panel B: boxplot + jittered points -- EVE size by family
eve_sizes_by_family = {}
for p in profiles.values():
    family = canon_family(p.get('likely_family'))
    if family not in FAMILY_COLORS:
        family = 'UNKNOWN'
    eve_sizes_by_family.setdefault(family, []).append(p['length'] / 1000)  # kb

# Only show families that have data, in family_order
families_present = [f for f in family_order if f in eve_sizes_by_family]
box_data = [eve_sizes_by_family[f] for f in families_present]
box_colors = [FAMILY_COLORS[f] for f in families_present]

if box_data:
    bp = ax2.boxplot(box_data, positions=range(len(families_present)),
                     widths=0.5, patch_artist=True, showfliers=False,
                     medianprops=dict(color='black', linewidth=1.5),
                     whiskerprops=dict(color='#555555'),
                     capprops=dict(color='#555555'))

    for patch, color in zip(bp['boxes'], box_colors):
        patch.set_facecolor(color)
        patch.set_alpha(0.4)
        patch.set_edgecolor(color)

    # Jittered data points
    rng = np.random.default_rng(42)
    for i, (family, sizes) in enumerate(zip(families_present, box_data)):
        jitter = rng.uniform(-0.15, 0.15, size=len(sizes))
        ax2.scatter(np.full(len(sizes), i) + jitter, sizes,
                    color=FAMILY_COLORS[family], s=18, alpha=0.7,
                    edgecolors='white', linewidths=0.3, zorder=5)

    ax2.set_xticks(range(len(families_present)))
    ax2.set_xticklabels(families_present)
else:
    ax2.text(0.5, 0.5, 'No canonical EVEs', ha='center', va='center',
             transform=ax2.transAxes)
    ax2.set_xticks([])
ax2.set_ylabel('EVE length (kb)')
ax2.set_title('(B) Size Distribution by Family', fontweight='bold')
finalize_axes(ax2)

fig.suptitle(f'{GENOME_ID} EVE Overview (n={len(profiles)})', fontsize=13, fontweight='bold')
plt.tight_layout()
plt.savefig(BASE / 'eve_confidence_tiers.png', dpi=300)
plt.show()

from IPython.display import FileLink
FileLink(str(BASE / 'eve_confidence_tiers.png'))

# %% [markdown]
# ## ANI Clustering of EVEs
#
# Groups the canonical EVEs by sequence similarity so that near-identical integrations become visible. skani computes all-versus-all average nucleotide identity, and two EVEs are linked when they clear both the ANI threshold and a minimum 50% aligned fraction; each connected component of the resulting graph is one cluster. Clustering runs only when at least three EVEs are present. Cluster assignments are carried onto the gene map and the marker heatmap below.

# %%
if len(profiles) < 3:
    print(f'Skipping ANI clustering: only {len(profiles)} EVEs (need >= 3)')
    eve_cluster_map = {eid: 'singleton' for eid in profiles}
    multi_clusters = []
else:
    # ---- ANI Clustering: canonical EVEs (skani, 90% ANI) ----
    import shutil
    
    CLUSTER_TIERS = SHOW_TIERS
    MIN_AF = 50.0
    
    # Auto-detect EVE FASTA (*_eves.fna)
    eve_fastas = sorted(BASE.glob('*_eves.fna'))
    assert eve_fastas, 'No *_eves.fna file found'
    FASTA_PATH = eve_fastas[0]
    
    SKANI_BIN = shutil.which('skani')
    if not SKANI_BIN:
        # Walk up from notebook dir to find virosync pixi env
        _search = Path('.').resolve()
        for _ in range(10):
            _candidate = _search / '.pixi' / 'envs' / 'default' / 'bin' / 'skani'
            if _candidate.exists():
                SKANI_BIN = str(_candidate)
                break
            if _search.parent == _search:
                break
            _search = _search.parent
    assert SKANI_BIN, 'skani not found on PATH or in virosync pixi env'
    
    # 1. Filter canonical sequences from the FASTA
    filtered_records = {}
    with open(FASTA_PATH) as f:
        current_id = None
        current_header = ""
        current_seq = []
        for line in f:
            line = line.rstrip('\n')
            if line.startswith('>'):
                if current_id and current_seq:
                    filtered_records[current_id] = (current_header, ''.join(current_seq))
                current_header = line
                fields = line.split()
                current_id = fields[0][1:]  # strip '>'
                tier = ''
                for field in fields:
                    if field.startswith('tier='):
                        tier = field.split('=', 1)[1]
                if tier not in CLUSTER_TIERS:
                    current_id = None  # skip this record
                current_seq = []
            elif current_id:
                current_seq.append(line)
        if current_id and current_seq:
            filtered_records[current_id] = (current_header, ''.join(current_seq))
    
    print(f'Filtered {len(filtered_records)} EVEs from tiers: {", ".join(CLUSTER_TIERS)}')
    
    # 2. Write individual FASTAs for skani (one per EVE) and run all-vs-all
    tmpdir = tempfile.mkdtemp(prefix="skani_cluster_")
    try:
        tmpdir_path = Path(tmpdir)
        fasta_list_path = tmpdir_path / "fasta_list.txt"
        eve_file_map = {}  # file path -> eve_id
        filename_components = safe_filename_components(filtered_records, label="EVE ID")

        with open(fasta_list_path, "w") as fl:
            for eve_id, (header, seq) in filtered_records.items():
                fpath = tmpdir_path / f"{filename_components[eve_id]}.fna"
                require_strict_child(tmpdir_path, fpath)
                with open(fpath, "w") as f:
                    f.write(f"{header}\n{seq}\n")
                fl.write(f"{fpath}\n")
                eve_file_map[str(fpath)] = eve_id
    
        ani_out = Path(tmpdir) / 'ani.tsv'
        cmd = [
            SKANI_BIN, 'triangle',
            '-l', str(fasta_list_path),
            '-E',                           # sparse output (row-by-row)
            '--medium',                     # better accuracy for small sequences
            '-m', '200',                    # lower marker compression for small genomes
            '-s', '80',                     # screen threshold
            '--min-af', str(int(MIN_AF)),   # minimum aligned fraction
            '-t', '4',
            '-o', str(ani_out),
        ]
    
        result = subprocess.run(cmd, capture_output=True, text=True)
        if result.returncode != 0:
            print(f'skani error:\n{result.stderr}')
            raise RuntimeError('skani triangle failed')
    
        # 3. Parse sparse output and cluster via union-find at ANI threshold
        parent = {eid: eid for eid in filtered_records}
    
        def find(x):
            while parent[x] != x:
                parent[x] = parent[parent[x]]
                x = parent[x]
            return x
    
        def union(a, b):
            ra, rb = find(a), find(b)
            if ra != rb:
                parent[ra] = rb
    
        n_edges = 0
        with open(ani_out) as f:
            next(f)  # skip header
            for line in f:
                cols = line.rstrip('\n').split('\t')
                ref_id = eve_file_map.get(cols[0], cols[0])
                query_id = eve_file_map.get(cols[1], cols[1])
                ani = float(cols[2])
                af_ref = float(cols[3])
                af_query = float(cols[4])
                if ani >= ANI_THRESHOLD and max(af_ref, af_query) >= MIN_AF:
                    union(ref_id, query_id)
                    n_edges += 1
    finally:
        # Clean up temp files
        shutil.rmtree(tmpdir, ignore_errors=True)
    
    print(f'skani pairs >= {ANI_THRESHOLD:.0f}% ANI: {n_edges}')
    
    # Connected components = clusters
    clusters_raw = defaultdict(list)
    for eid in filtered_records:
        clusters_raw[find(eid)].append(eid)
    
    # 4. Assign cluster labels sorted by size desc; singletons get "singleton"
    eve_cluster_map = {}
    multi_clusters = sorted(
        [(rep, members) for rep, members in clusters_raw.items() if len(members) > 1],
        key=lambda x: -len(x[1]),
    )
    
    for idx, (rep, members) in enumerate(multi_clusters, start=1):
        label = f'Cluster_{idx}'
        for m in members:
            eve_cluster_map[m] = label
    
    for rep, members in clusters_raw.items():
        if len(members) == 1:
            eve_cluster_map[members[0]] = 'singleton'
    
    # 5. Print summary
    n_clustered = sum(1 for v in eve_cluster_map.values() if v != 'singleton')
    n_singletons = sum(1 for v in eve_cluster_map.values() if v == 'singleton')
    print(f'\nClusters: {len(multi_clusters)} multi-member, {n_singletons} singletons')
    print(f'Clustered EVEs: {n_clustered}/{len(filtered_records)}')
    
    print(f'\n{"Cluster":<14} {"Size":>5}  {"Tiers":<20} {"Members"}')
    print('-' * 80)
    for idx, (rep, members) in enumerate(multi_clusters, start=1):
        tiers = []
        for m in members:
            for field in filtered_records[m][0].split():
                if field.startswith('tier='):
                    tiers.append(field.split('=')[1])
        tier_str = ', '.join(sorted(set(tiers)))
        member_short = [m.split('_', 1)[1] if '_' in m else m for m in members]
        print(f'Cluster_{idx:<5} {len(members):>5}  {tier_str:<20} {", ".join(member_short)}')
    
    print(f'\nCluster map stored in eve_cluster_map ({len(eve_cluster_map)} entries)')
    
    # 6. Pie chart: cluster size distribution
    labels = []
    sizes = []
    pie_colors = []
    cmap = plt.cm.Set2
    for idx, (rep, members) in enumerate(multi_clusters, start=1):
        labels.append(f'Cluster {idx} (n={len(members)})')
        sizes.append(len(members))
        pie_colors.append(cmap(idx / max(len(multi_clusters) + 1, 2)))
    if n_singletons > 0:
        labels.append(f'Singletons (n={n_singletons})')
        sizes.append(n_singletons)
        pie_colors.append('#BBBBBB')
    
    fig, ax = plt.subplots(figsize=(3, 3))
    wedges, texts, autotexts = ax.pie(
        sizes, labels=labels, autopct='%1.0f%%',
        colors=pie_colors, startangle=90,
        pctdistance=0.82, textprops={'fontsize': 9})
    for t in autotexts:
        t.set_fontsize(8)
    ax.set_title(f'ANI Cluster Composition (n={len(eve_cluster_map)} EVEs, {ANI_THRESHOLD:.0f}% ANI)')
    plt.tight_layout()
    plt.savefig(BASE / 'eve_cluster_composition.png', dpi=300)
    plt.show()
    
    from IPython.display import FileLink
    FileLink(str(BASE / 'eve_cluster_composition.png'))

# %% [markdown]
# ## EVE Gene Map with Flanking Context
#
# Each canonical EVE is drawn with its flanking host context. Every Prodigal gene in the displayed span is shown. The gray flanks cover `FLANK_SIZE` (5 kb by default) and extend when needed to include the three nearest genes on each side. Arrow direction follows the Prodigal strand. Most arrows are colored by their best protein hit; eukaryotic hits that share the dominant Phase 1 host lineage are separated from other eukaryotes. Gold stars mark validated MCPs. The underlying MCP arrow uses the highest-ranked viral top-10 hit with at least 25% amino-acid identity. This prevents a duplicate cellular entry from obscuring independent viral taxonomy evidence for the validated marker. Legacy PHAGE targets whose resolved lineage belongs to Preplasmiviricota are shown as PPV. The white interval is the final ViroSync boundary.

# %%
if not profiles:
    print('No EVEs to map.')
    eve_genes_extended = {}
else:
    # ---- Build extended gene map data ----
    
    NEAREST_FLANK_GENES = 3

    def _clean_text(value):
        return '' if value is None or pd.isna(value) else str(value)

    def classify_gene(origin, target, taxonomy_record, is_marker=False):
        """Map one gene's evidence to its report display category."""
        if is_marker:
            marker_category = _marker_viral_category(taxonomy_record)
            if marker_category:
                return marker_category
        viral_category = _canonical_viral_category(origin, target)
        if viral_category:
            return viral_category
        if origin == 'EUK':
            return 'HOST' if is_host_gene(target) else 'EUK'
        if origin == 'HOST_SPECIFIC':
            return 'HOST'
        if origin == 'BAC':
            return 'BAC'
        if origin == 'ARC':
            return 'ARC'
        return 'UNKNOWN'

    def _make_gene_record(gene, region):
        porf_id = gene['porf_id']
        taxonomy_record = BOUNDARY_TAXONOMY.get(porf_id, {})
        origin = _clean_text(taxonomy_record.get('top1_prefix')).rstrip('_')
        origin = origin if origin else 'UNKNOWN'
        target = _clean_text(taxonomy_record.get('top1_target'))
        jr_info = jelly_roll_map.get(porf_id, {})
        is_mcp = porf_id in mcp_porf_ids
        return {
            'start': gene['start'],
            'end': gene['end'],
            'strand': gene['strand'],
            'category': classify_gene(
                origin,
                target,
                taxonomy_record,
                is_marker=is_mcp,
            ),
            'best_hit_origin': origin,
            'best_hit_target': target,
            'is_capsid': porf_id in jelly_roll_map,
            'is_mcp': is_mcp,
            'is_rt': porf_id in rt_gene_ids,
            'porf_id': porf_id,
            'host_lineage_match': origin == 'EUK' and is_host_gene(target),
            'jr_type': jr_info.get('type', ''),
            'jr_confidence': jr_info.get('confidence', 0),
            'region': region,
        }

    eve_genes_extended = {}
    for eve_id, profile in profiles.items():
        eve_start = int(profile.get('start', 0))
        eve_end = int(profile.get('end', 0))
        scaffold = str(profile.get('scaffold', ''))
        scaffold_genes = proteome_genes_by_scaffold.get(scaffold, [])

        core_genes_for_eve = [
            gene for gene in scaffold_genes
            if gene['start'] < eve_end and gene['end'] > eve_start
        ]
        left_candidates = [
            gene for gene in scaffold_genes
            if gene['end'] <= eve_start
        ]
        right_candidates = [
            gene for gene in scaffold_genes
            if gene['start'] >= eve_end
        ]
        nearest_left_ids = {
            gene['porf_id']
            for gene in sorted(
                left_candidates,
                key=lambda gene: (eve_start - gene['end'], -gene['end']),
            )[:NEAREST_FLANK_GENES]
        }
        nearest_right_ids = {
            gene['porf_id']
            for gene in sorted(
                right_candidates,
                key=lambda gene: (gene['start'] - eve_end, gene['start']),
            )[:NEAREST_FLANK_GENES]
        }
        left_genes = [
            gene for gene in left_candidates
            if gene['end'] >= eve_start - FLANK_SIZE
            or gene['porf_id'] in nearest_left_ids
        ]
        right_genes = [
            gene for gene in right_candidates
            if gene['start'] <= eve_end + FLANK_SIZE
            or gene['porf_id'] in nearest_right_ids
        ]

        ext_start = max(0, eve_start - FLANK_SIZE)
        if left_genes:
            ext_start = min(ext_start, min(gene['start'] for gene in left_genes))
        ext_end = eve_end + FLANK_SIZE
        if right_genes:
            ext_end = max(ext_end, max(gene['end'] for gene in right_genes))

        eve_genes_extended[eve_id] = {
            'eve_start': eve_start,
            'eve_end': eve_end,
            'scaffold': scaffold,
            'ext_start': ext_start,
            'ext_end': ext_end,
            'length': ext_end - ext_start,
            'eve_length': eve_end - eve_start,
            'status': profile.get('status', ''),
            'confidence': profile.get('final_confidence', 0),
            'confidence_tier': profile.get('confidence_tier', ''),
            'likely_family': profile.get('likely_family', ''),
            'left_flank_genes': [
                _make_gene_record(gene, 'left_flank') for gene in left_genes
            ],
            'eve_genes': [
                _make_gene_record(gene, 'eve') for gene in core_genes_for_eve
            ],
            'right_flank_genes': [
                _make_gene_record(gene, 'right_flank') for gene in right_genes
            ],
        }
    
    total_eve = sum(len(e['eve_genes']) for e in eve_genes_extended.values())
    total_left = sum(len(e['left_flank_genes']) for e in eve_genes_extended.values())
    total_right = sum(len(e['right_flank_genes']) for e in eve_genes_extended.values())
    print(f'Gene mapping: {total_eve} core, {total_left} left flank, {total_right} right flank')
    
    # ---- Layout constants for gene map ----
    BAR_HEIGHT = 0.5
    LABEL_FONT = 8
    CONF_FONT = 8
    LEGEND_FONT = 9
    TITLE_FONT = 13
    XLABEL_FONT = 10
    FLANK_COLOR = '#F0F0F0'
    FLANK_EDGE = '#AAAAAA'
    CORE_EDGE = '#333333'
    LABEL_X_FRAC = 0.22
    CONF_X_PAD_FRAC = 0.01
    SCALE_BAR_BP = 5000
    EVE_SPACING = 0.32
    
    MARKER_DJR = dict(marker='*', markersize=12, color='white',
                      markeredgecolor='#000000', markeredgewidth=1.2, zorder=10)
    MARKER_SJR = dict(marker='*', markersize=12, color='white',
                      markeredgecolor='#0077BB', markeredgewidth=1.2, zorder=10)
    MARKER_RT  = dict(marker='^', markersize=8, color='white',
                      markeredgecolor='#222222', markeredgewidth=1.0, zorder=9)
    # MCP (major capsid) marker genes: yellow star, black outline -- easy to spot.
    MARKER_MCP = dict(marker='*', markersize=14, color='#FFD400',
                      markeredgecolor='#000000', markeredgewidth=1.2, zorder=11)
    
    TIER_COLORS = {'HIGH': '#333333', 'MEDIUM': '#777777', 'LOW': '#BBBBBB'}
    TIER_ORDER = {'HIGH': 0, 'MEDIUM': 1, 'LOW': 2}

# %%
if not eve_genes_extended:
    print('No EVEs to map.')
else:
    # ---- Gene Map: all canonical EVEs with colored flanking genes ----
    # Shows every canonical EVE in a single figure with tier-colored labels
    
    ALL_SHOW_TIERS = SHOW_TIERS
    
    def sort_key_all(item):
        _, info = item
        tier_rank = TIER_ORDER.get(info['confidence_tier'], 3)
        return (tier_rank, -info['confidence'], -info['eve_length'])
    
    all_sorted_eves = sorted(
        [(eid, info) for eid, info in eve_genes_extended.items()
         if info['confidence_tier'] in ALL_SHOW_TIERS],
        key=sort_key_all,
    )
    
    print(f'Showing {len(all_sorted_eves)} EVEs (tiers: {", ".join(ALL_SHOW_TIERS)})')
    
    n_all = len(all_sorted_eves)
    fig_h = max(22, n_all * EVE_SPACING)
    fig, ax = plt.subplots(figsize=(18, fig_h))
    
    max_len = max(e[1]['length'] for e in all_sorted_eves)
    
    for i, (eve_id, eve_info) in enumerate(all_sorted_eves):
        y = n_all - 1 - i
        total_length = eve_info['length']
        eve_start_rel = eve_info['eve_start'] - eve_info['ext_start']
        eve_end_rel = eve_info['eve_end'] - eve_info['ext_start']
        confidence = eve_info['confidence']
        tier = eve_info['confidence_tier']
        # Background: gray flanks, white EVE core
        ax.barh(y, eve_start_rel, left=0, height=BAR_HEIGHT,
                color=FLANK_COLOR, edgecolor=FLANK_EDGE, linewidth=0.5)
        ax.barh(y, eve_end_rel - eve_start_rel, left=eve_start_rel, height=BAR_HEIGHT,
                color='white', edgecolor=CORE_EDGE, linewidth=1.0)
        ax.barh(y, total_length - eve_end_rel, left=eve_end_rel, height=BAR_HEIGHT,
                color=FLANK_COLOR, edgecolor=FLANK_EDGE, linewidth=0.5)
    
        # Draw genes
        djr_pos, sjr_pos, rt_pos, mcp_pos = [], [], [], []
        all_genes = (
            eve_info['left_flank_genes']
            + eve_info['eve_genes']
            + eve_info['right_flank_genes']
        )
        for gene in all_genes:
            gs = max(0, gene['start'] - eve_info['ext_start'])
            ge = min(total_length, gene['end'] - eve_info['ext_start'])
            if ge <= gs:
                continue
            gw = ge - gs
            color = COLORS.get(gene['category'], COLORS['UNKNOWN'])
            alpha = 0.95 if gene['region'] == 'eve' else 0.70

            half_height = BAR_HEIGHT * 0.4
            head_width = min(gw * 0.45, 300)
            if gene['strand'] == '+':
                points = [
                    (gs, y - half_height),
                    (ge - head_width, y - half_height),
                    (ge, y),
                    (ge - head_width, y + half_height),
                    (gs, y + half_height),
                ]
            elif gene['strand'] == '-':
                points = [
                    (gs, y),
                    (gs + head_width, y - half_height),
                    (ge, y - half_height),
                    (ge, y + half_height),
                    (gs + head_width, y + half_height),
                ]
            else:
                points = [
                    (gs, y - half_height),
                    (ge, y - half_height),
                    (ge, y + half_height),
                    (gs, y + half_height),
                ]
            gene_arrow = mpatches.Polygon(
                points,
                closed=True,
                facecolor=color, edgecolor='none', alpha=alpha, zorder=5,
            )
            ax.add_patch(gene_arrow)
    
            midx = gs + gw / 2
            if gene.get('is_mcp'):
                mcp_pos.append(midx)
            elif gene.get('is_capsid'):
                jr_type = gene.get('jr_type', '')
                (djr_pos if jr_type != 'SJR' else sjr_pos).append(midx)
            if gene.get('is_rt'):
                rt_pos.append(midx)
    
        for mx in djr_pos:
            ax.plot(mx, y, **MARKER_DJR)
        for mx in sjr_pos:
            ax.plot(mx, y, **MARKER_SJR)
        for mx in rt_pos:
            ax.plot(mx, y, **MARKER_RT)
        for mx in mcp_pos:
            ax.plot(mx, y, **MARKER_MCP)
    
        # EVE label (left side) -- color by tier
        parts = eve_id.replace('EVE_', '').rsplit('_', 1)
        if len(parts) == 2:
            scaffold_short = parts[0].split('|')[1] if '|' in parts[0] else parts[0]
            label = f'{scaffold_short} ({parts[1]})'
        else:
            label = eve_id.replace('EVE_', '')[:30]
    
        tier_color = TIER_COLORS.get(tier, '#666666')
        ax.text(-max_len * 0.01, y, label, ha='right', va='center',
                fontsize=LABEL_FONT, color=tier_color,
                fontweight='bold' if tier == 'HIGH' else 'normal')
    
        # Confidence score (right side)
        ax.text(total_length + max_len * CONF_X_PAD_FRAC, y, f'{confidence:.2f}',
                ha='left', va='center', fontsize=CONF_FONT, color='#555555')
    
    # ---- Tier separator lines + margin labels ----
    tier_spans_all = {}
    running = 0
    for t in ['HIGH', 'MEDIUM', 'LOW']:
        count = sum(1 for _, e in all_sorted_eves if e['confidence_tier'] == t)
        if count > 0:
            tier_spans_all[t] = (running, running + count)
            running += count
    
    for tier_name, (idx_start, idx_end) in tier_spans_all.items():
        if idx_end > idx_start:
            mid_y = n_all - 1 - (idx_start + idx_end) / 2 + 0.5
            n_tier = idx_end - idx_start
            ax.text(-max_len * LABEL_X_FRAC * 0.92, mid_y,
                    f'{tier_name}\n(n={n_tier})',
                    ha='center', va='center', fontsize=9, fontweight='bold',
                    color=TIER_COLORS.get(tier_name, '#666666'),
                    bbox=dict(boxstyle='round,pad=0.3', facecolor='white',
                              edgecolor='#CCCCCC', alpha=0.9))
    
    # ---- Axes formatting ----
    tier_str_all = ' / '.join(f'{sum(1 for _, e in all_sorted_eves if e["confidence_tier"]==t)} {t}'
                               for t in ['HIGH', 'MEDIUM', 'LOW']
                               if any(e['confidence_tier'] == t for _, e in all_sorted_eves))
    
    ax.set_xlim(-max_len * LABEL_X_FRAC, max_len * 1.08)
    ax.set_ylim(-1.5, n_all - 0.2)
    ax.set_xlabel(
        f'Position (bp) | Gray: {FLANK_SIZE / 1000:g} kb minimum + '
        f'{NEAREST_FLANK_GENES} nearest genes per flank | White: EVE core',
        fontsize=XLABEL_FONT,
    )
    ax.set_title(
        f'{GENOME_ID} EVE Gene Map: All Confident EVEs  ({tier_str_all})',
        fontsize=TITLE_FONT, fontweight='bold',
    )
    ax.set_yticks([])
    ax.spines['left'].set_visible(False)
    ax.spines['right'].set_visible(False)
    ax.spines['top'].set_visible(False)
    
    # Scale bar
    sb_x = max_len * 0.82
    ax.plot([sb_x, sb_x + SCALE_BAR_BP], [-1.1, -1.1], 'k-', linewidth=2)
    ax.text(sb_x + SCALE_BAR_BP / 2, -1.3, '5 kb', ha='center', fontsize=9)
    
    # Legend
    legend_elements = [
        mpatches.Patch(facecolor=COLORS['PPV'], label='PPV / Preplasmiviricota'),
        mpatches.Patch(facecolor=COLORS['MIRUS'], label='Mirusviricota'),
        mpatches.Patch(facecolor=COLORS['NCLDV'], label='NCLDV'),
        mpatches.Patch(facecolor=COLORS['GVMAG'], label='Giant-virus MAG'),
        mpatches.Patch(facecolor=COLORS['PHAGE'], label='Phage'),
        mpatches.Patch(
            facecolor=COLORS['HOST'],
            label=f'Host lineage ({HOST_GENUS.title()})' if HOST_GENUS else 'Host lineage',
        ),
        mpatches.Patch(facecolor=COLORS['EUK'], label='Other Eukaryote'),
        mpatches.Patch(facecolor=COLORS['BAC'], label='Bacteria'),
        mpatches.Patch(facecolor=COLORS['ARC'], label='Archaea'),
        mpatches.Patch(facecolor=COLORS['UNKNOWN'], label='Unknown'),
    ]
    if mcp_porf_ids:
        legend_elements.append(
            Line2D([0], [0], **{k: v for k, v in MARKER_MCP.items()
                    if k != 'zorder'}, label='MCP (major capsid)'),
        )
    if jelly_roll_map:
        legend_elements.extend([
            Line2D([0], [0], **{k: v for k, v in MARKER_DJR.items()
                    if k != 'zorder'}, label='DJR MCP (structural)'),
            Line2D([0], [0], **{k: v for k, v in MARKER_SJR.items()
                    if k != 'zorder'}, label='SJR MCP (structural)'),
        ])
    if rt_gene_ids:
        legend_elements.append(
            Line2D([0], [0], **{k: v for k, v in MARKER_RT.items()
                    if k != 'zorder'}, label='RT gene (PF00078)'),
        )
    legend_elements.extend([
        mpatches.Patch(facecolor=FLANK_COLOR, edgecolor=FLANK_EDGE, label='Flanking region'),
        mpatches.Patch(facecolor='white', edgecolor=CORE_EDGE, label='EVE core'),
    ])
    
    # Tier indicator in legend
    legend_elements.extend([
        Line2D([0], [0], color='none', label=''),  # spacer
        Line2D([0], [0], marker='s', color='none', markerfacecolor=TIER_COLORS['HIGH'],
               markersize=8, label='HIGH confidence'),
        Line2D([0], [0], marker='s', color='none', markerfacecolor=TIER_COLORS['MEDIUM'],
               markersize=8, label='MEDIUM confidence'),
    ])
    
    ax.legend(handles=legend_elements, loc='upper right', framealpha=0.95,
              fontsize=LEGEND_FONT, ncol=2)
    
    plt.tight_layout()
    plt.savefig(BASE / 'eve_gene_map_with_flanks.png', dpi=300, bbox_inches='tight',
                facecolor='white')
    plt.show()
    
    
    # Flanking region gene counts (used by gene-distribution cell)
    all_shown_ids = {eid for eid, _ in all_sorted_eves}
    flank_cats_left = Counter()
    flank_cats_right = Counter()
    eve_cats = Counter()
    
    for eve_id, info in eve_genes_extended.items():
        if eve_id not in all_shown_ids:
            continue
        for g in info['left_flank_genes']:
            flank_cats_left[g['category']] += 1
        for g in info['right_flank_genes']:
            flank_cats_right[g['category']] += 1
        for g in info['eve_genes']:
            eve_cats[g['category']] += 1
    
    from IPython.display import FileLink
    FileLink(str(BASE / 'eve_gene_map_with_flanks.png'))

# %% [markdown]
# ## Detailed Gene Contexts
#
# The overview above uses one common horizontal scale, which makes short loci hard to inspect when a genome also contains long calls. This figure redraws up to six of the shortest calls from the highest available confidence tier on independent axes so that gene order remains visible. It uses HIGH calls when present, then MEDIUM or LOW. The plot is a report view, not an additional filtering step. Coordinates are relative to each predicted EVE start, dashed lines mark its boundaries, gray outlines mark flanking genes, and arrow direction follows the retained Prodigal strand.

# %%
if not eve_genes_extended:
    print('No EVEs available for detailed gene contexts.')
else:
    DETAIL_MAX_EVES = 6
    detail_tier = next(
        (
            tier
            for tier in ['HIGH', 'MEDIUM', 'LOW']
            if any(
                info['confidence_tier'] == tier
                for info in eve_genes_extended.values()
            )
        ),
        None,
    )
    detail_eves = sorted(
        [
            (eve_id, info)
            for eve_id, info in eve_genes_extended.items()
            if info['confidence_tier'] == detail_tier
        ],
        key=lambda item: (item[1]['eve_length'], -item[1]['confidence']),
    )[:DETAIL_MAX_EVES]

    if not detail_eves:
        print('No confident EVEs available for detailed gene contexts.')
    else:
        n_detail = len(detail_eves)
        fig, axes = plt.subplots(
            n_detail,
            1,
            figsize=(11, max(3.4, 1.45 * n_detail + 1.4)),
            squeeze=False,
        )
        axes = axes[:, 0]
        detail_categories = set()

        for ax, (eve_id, eve_info) in zip(axes, detail_eves):
            eve_start = eve_info['eve_start']
            eve_length_kb = eve_info['eve_length'] / 1000
            all_genes = (
                eve_info['left_flank_genes']
                + eve_info['eve_genes']
                + eve_info['right_flank_genes']
            )
            xmin = (eve_info['ext_start'] - eve_start) / 1000
            xmax = (eve_info['ext_end'] - eve_start) / 1000
            padding = max((xmax - xmin) * 0.025, 0.25)
            head_kb = max((xmax - xmin) * 0.012, 0.06)

            ax.axvspan(0, eve_length_kb, color='#0077BB', alpha=0.07, zorder=0)
            ax.broken_barh(
                [(0, eve_length_kb)],
                (0.72, 0.08),
                facecolors='#0077BB',
                edgecolors='none',
                alpha=0.80,
                zorder=2,
            )
            for boundary in (0, eve_length_kb):
                ax.axvline(
                    boundary,
                    color='#0077BB',
                    linewidth=0.8,
                    linestyle='--',
                    alpha=0.75,
                    zorder=1,
                )

            for gene in all_genes:
                start = (gene['start'] - eve_start) / 1000
                end = (gene['end'] - eve_start) / 1000
                width = end - start
                if width <= 0:
                    continue
                strand = gene.get('strand', '.')
                direction = width if strand == '+' else -width
                x = start if strand == '+' else end
                edge = '#555555' if gene['region'] != 'eve' else 'white'
                detail_categories.add(gene['category'])
                ax.add_patch(
                    mpatches.FancyArrow(
                        x,
                        0.40,
                        direction,
                        0,
                        width=0.18,
                        head_width=0.30,
                        head_length=min(width * 0.45, head_kb),
                        length_includes_head=True,
                        facecolor=COLORS.get(gene['category'], COLORS['UNKNOWN']),
                        edgecolor=edge,
                        linewidth=0.45,
                        alpha=0.82 if gene['region'] != 'eve' else 0.96,
                        zorder=4,
                    )
                )
                marker_x = (start + end) / 2
                if gene.get('is_mcp'):
                    ax.plot(marker_x, 0.64, **MARKER_MCP)
                elif gene.get('is_capsid'):
                    marker = MARKER_SJR if gene.get('jr_type') == 'SJR' else MARKER_DJR
                    ax.plot(marker_x, 0.64, **marker)
                if gene.get('is_rt'):
                    ax.plot(marker_x, 0.64, **MARKER_RT)

            short_id = eve_id.replace('EVE_', '')
            if len(short_id) > 64:
                short_id = f'{short_id[:30]}…{short_id[-30:]}'
            ax.text(
                0,
                1.03,
                short_id,
                transform=ax.transAxes,
                ha='left',
                va='bottom',
                fontsize=8,
                fontweight='bold',
            )
            ax.text(
                1,
                1.03,
                f'{eve_info["likely_family"]} | {eve_info["eve_length"] / 1000:.1f} kb '
                f'| score {eve_info["confidence"]:.2f}',
                transform=ax.transAxes,
                ha='right',
                va='bottom',
                fontsize=7.5,
            )
            ax.set_xlim(xmin - padding, xmax + padding)
            ax.set_ylim(0, 1)
            ax.set_yticks([])
            ax.tick_params(axis='x', labelsize=7)
            finalize_axes(ax, despine_left=True)

        axes[-1].set_xlabel('Position relative to predicted EVE start (kb)')
        fig.suptitle(
            f'{GENOME_ID}: Detailed {detail_tier}-confidence EVE Gene Contexts',
            fontsize=13,
            fontweight='bold',
        )

        detail_order = [
            'PPV', 'MIRUS', 'NCLDV', 'GVMAG', 'CRESS', 'PHAGE',
            'HOST', 'EUK', 'BAC', 'ARC', 'UNKNOWN',
        ]
        detail_labels = {
            'PPV': 'PPV / Preplasmiviricota',
            'MIRUS': 'Mirusviricota',
            'NCLDV': 'NCLDV',
            'GVMAG': 'Giant-virus MAG',
            'CRESS': 'CRESS',
            'PHAGE': 'Phage',
            'HOST': f'Host lineage ({HOST_GENUS.title()})' if HOST_GENUS else 'Host lineage',
            'EUK': 'Other eukaryote',
            'BAC': 'Bacteria',
            'ARC': 'Archaea',
            'UNKNOWN': 'Unknown',
        }
        detail_handles = [
            mpatches.Patch(
                facecolor=COLORS[category],
                label=detail_labels[category],
            )
            for category in detail_order
            if category in detail_categories
        ]
        detail_handles.extend([
            mpatches.Patch(
                facecolor='white',
                edgecolor='#555555',
                label='Gray outline: flanking gene',
            ),
            Line2D(
                [0],
                [0],
                **{k: v for k, v in MARKER_MCP.items() if k != 'zorder'},
                label='MCP',
            ),
        ])
        fig.legend(
            handles=detail_handles,
            loc='lower center',
            bbox_to_anchor=(0.5, 0.01),
            ncol=4,
            frameon=False,
            fontsize=7,
        )
        plt.tight_layout(rect=[0, 0.12, 1, 0.96])
        plt.savefig(
            BASE / 'eve_gene_context_high.png',
            dpi=300,
            bbox_inches='tight',
            facecolor='white',
        )
        plt.show()

        from IPython.display import FileLink
        FileLink(str(BASE / 'eve_gene_context_high.png'))

# %% [markdown]
# ## Gene Category Distribution: Core vs Flanking
#
# Summarizes the gene map as fractions rather than individual loci. Each bar is one region (left flank, EVE core, or right flank) split into the fraction of genes in each taxonomy category, with the gene count for that region printed on the axis. A core weighted toward viral categories (PPV, NCLDV, Mirusviricota) beside flanks weighted toward host and eukaryotic genes is consistent with a true integration. Viral genes reaching into the flanks, or host genes filling the core, mark a boundary worth a closer look.

# %%
if not eve_genes_extended:
    print('No data for gene distribution.')
else:
    # ---- Stacked bar: core vs flank gene composition ----
    categories_all = [
        'PPV', 'NCLDV', 'MIRUS', 'GVMAG', 'CRESS', 'PHAGE',
        'HOST', 'EUK', 'BAC', 'ARC', 'UNKNOWN'
    ]
    regions = ['Left Flank', 'EVE Core', 'Right Flank']
    region_counters = [flank_cats_left, eve_cats, flank_cats_right]
    region_totals = [sum(rc.values()) for rc in region_counters]
    
    fig, ax = plt.subplots(figsize=(5.5, 3.5))
    x = np.arange(len(regions))
    width = 0.55
    
    bottoms = np.zeros(len(regions))
    for cat in categories_all:
        vals = np.array([rc.get(cat, 0) for rc in region_counters], dtype=float)
        totals = np.array(region_totals, dtype=float)
        totals[totals == 0] = 1
        fracs = vals / totals
        ax.bar(x, fracs, width, bottom=bottoms, label=cat,
               color=COLORS[cat], edgecolor='white', linewidth=0.8)
        bottoms += fracs
    
    ax.set_xticks(x)
    ax.set_xticklabels([f'{r}\n(n={t})' for r, t in zip(regions, region_totals)])
    ax.set_ylabel('Fraction of genes')
    ax.set_ylim(0, 1.0)
    ax.set_title('Gene Taxonomy Composition by Region', fontsize=13, fontweight='bold')
    ax.legend(fontsize=8, loc='upper left', bbox_to_anchor=(1.02, 1), borderaxespad=0)
    finalize_axes(ax)
    plt.tight_layout()
    plt.savefig(BASE / 'eve_gene_category_distribution.png', dpi=300, bbox_inches='tight')
    plt.show()
    
    from IPython.display import FileLink
    FileLink(str(BASE / 'eve_gene_category_distribution.png'))


# %% [markdown]
# ## Marker and InterProScan Summary
#
# Two views of the hallmark and functional content of the EVEs. The heatmap has one row per EVE and one column per marker, colored by copy number, with cells of two or more copies labeled and rows ordered by hierarchical clustering on marker presence and absence. Two annotation strips sit beside the rows, one for the ANI cluster and one for the likely family. Markers absent from every EVE are dropped. The second view summarizes marker, family, and InterProScan keyword composition across the call set. A copy number above one marks a hallmark gene present in multiple copies within a single element.

# %%
if not profiles:
    print('No EVEs for marker heatmap.')
else:
    # ---- Marker Gene Copy Number Heatmap ----
    from scipy.cluster.hierarchy import linkage, leaves_list
    from scipy.spatial.distance import pdist
    import matplotlib.colors as mcolors
    from matplotlib.lines import Line2D as _Line2D
    
    # 1. Build copy-number matrix from hallmark_genes
    all_marker_names = set()
    marker_copy = {}
    for eve_id in profiles:
        counts = Counter(profiles[eve_id].get('hallmark_genes', []))
        marker_copy[eve_id] = counts
        all_marker_names.update(counts.keys())
    
    marker_names = sorted(all_marker_names)
    marker_df = pd.DataFrame(0, index=list(profiles.keys()), columns=marker_names, dtype=int)
    for eve_id, counts in marker_copy.items():
        for m, c in counts.items():
            marker_df.loc[eve_id, m] = c
    
    print(f'Marker matrix: {marker_df.shape[0]} EVEs x {marker_df.shape[1]} markers')
    max_initial_copy = int(marker_df.values.max()) if marker_df.size else 0
    print(f'Copy number range: 0\u2013{max_initial_copy}')
    
    # Drop all-zero columns
    marker_df = marker_df.loc[:, marker_df.sum(axis=0) > 0]
    if marker_df.shape[1] == 0:
        marker_df['no_marker_hits'] = 0
    
    # 2. Hierarchical clustering on ROWS (Jaccard on presence/absence)
    binary = (marker_df > 0).astype(int)
    if binary.shape[0] > 2:
        row_dist = pdist(binary.values, metric='jaccard')
        row_link = linkage(row_dist, method='average')
        row_leaves = leaves_list(row_link)
        marker_df = marker_df.iloc[row_leaves]
    
    # 3. Hierarchical clustering on COLUMNS (Jaccard on presence/absence)
    binary = (marker_df > 0).astype(int)
    if binary.shape[1] > 2:
        col_dist = pdist(binary.T.values, metric='jaccard')
        col_link = linkage(col_dist, method='average')
        col_leaves = leaves_list(col_link)
        marker_df = marker_df.iloc[:, col_leaves]
    
    # 4. Discrete colormap
    max_cn = int(marker_df.values.max())
    _cn_palette = [
        '#FFFFFF',   # 0 - white
        '#FFFFB2',   # 1 - pale yellow
        '#FECC5C',   # 2 - gold
        '#FD8D3C',   # 3 - orange
        '#E31A1C',   # 4 - red
        '#800026',   # 5 - dark maroon
    ]
    cn_colors = [_cn_palette[min(i, len(_cn_palette) - 1)] for i in range(max_cn + 1)]
    cmap = mcolors.ListedColormap(cn_colors)
    bounds = np.arange(-0.5, max_cn + 1.5, 1)
    norm = mcolors.BoundaryNorm(bounds, cmap.N)
    
    # 5. Cluster palette (cool/blue tones -- distinct from FAMILY_COLORS which are warm)
    unique_clusters = sorted(set(eve_cluster_map.values()) - {'singleton'})
    _cluster_colors = ['#4477AA', '#66CCEE', '#AA3377', '#CCBB44', '#228833']
    cluster_cpal = {cl: _cluster_colors[i % len(_cluster_colors)]
                    for i, cl in enumerate(unique_clusters)}
    cluster_cpal['singleton'] = '#E8E8E8'
    
    # 6. Figure layout
    n_rows, n_cols = marker_df.shape
    row_h = 0.20
    fig_h = n_rows * row_h
    fig, axes = plt.subplots(
        1, 3, figsize=(9, fig_h),
        gridspec_kw={'width_ratios': [0.5, 0.5, 10], 'wspace': 0.02},
    )
    ax_cl, ax_fam, ax_heat = axes
    
    # Heatmap
    im = ax_heat.imshow(marker_df.values, aspect='auto', cmap=cmap, norm=norm,
                        interpolation='nearest')
    
    # Gridlines (light gray so they show on white cells)
    for r in range(n_rows + 1):
        ax_heat.axhline(r - 0.5, color='#DDDDDD', linewidth=0.3)
    for c in range(n_cols + 1):
        ax_heat.axvline(c - 0.5, color='#DDDDDD', linewidth=0.3)
    
    # Annotate cells with copy number >= 2
    for r in range(n_rows):
        for c in range(n_cols):
            val = marker_df.values[r, c]
            if val >= 2:
                txt_color = 'white' if val >= 4 else '#333333'
                ax_heat.text(c, r, str(val), ha='center', va='center',
                            fontsize=6, fontweight='bold', color=txt_color)
    
    # Column labels on top
    ax_heat.xaxis.tick_top()
    ax_heat.set_xticks(range(n_cols))
    ax_heat.set_xticklabels(marker_df.columns, rotation=45, ha='left', fontsize=8)
    ax_heat.set_yticks([])
    ax_heat.tick_params(axis='x', top=False, bottom=False)
    
    # Short row labels
    short_labels = []
    for eid in marker_df.index:
        s = eid.replace(EVE_PREFIX + '|', '')
        parts = s.split('_', 1)
        if len(parts) == 2 and parts[0] == 'contig':
            num_rest = parts[1].split('_', 1)
            if len(num_rest) == 2:
                short_labels.append(f'c{num_rest[0]}:{num_rest[1]}')
            else:
                short_labels.append(s[:25])
        else:
            short_labels.append(s[:25])
    
    # ANI Cluster annotation strip
    for i, eid in enumerate(marker_df.index):
        cl = eve_cluster_map.get(eid, 'singleton')
        ax_cl.add_patch(plt.Rectangle((0, i - 0.5), 1, 1,
                        facecolor=cluster_cpal.get(cl, '#E8E8E8'), edgecolor='none'))
    ax_cl.set_xlim(0, 1)
    ax_cl.set_ylim(-0.5, n_rows - 0.5)
    ax_cl.set_yticks(range(n_rows))
    ax_cl.set_yticklabels(short_labels, fontsize=6)
    ax_cl.set_xticks([0.5])
    ax_cl.set_xticklabels(['ANI Cluster'], rotation=90, fontsize=7, ha='center')
    ax_cl.xaxis.tick_top()
    ax_cl.tick_params(axis='x', top=False)
    ax_cl.invert_yaxis()
    
    # Category annotation strip
    for i, eid in enumerate(marker_df.index):
        fam = canon_family(profiles[eid].get('likely_family'))
        ax_fam.add_patch(plt.Rectangle((0, i - 0.5), 1, 1,
                        facecolor=FAMILY_COLORS.get(fam, '#BBBBBB'), edgecolor='none'))
    ax_fam.set_xlim(0, 1)
    ax_fam.set_ylim(-0.5, n_rows - 0.5)
    ax_fam.set_yticks([])
    ax_fam.set_xticks([0.5])
    ax_fam.set_xticklabels(['Category'], rotation=90, fontsize=7, ha='center')
    ax_fam.xaxis.tick_top()
    ax_fam.tick_params(axis='x', top=False)
    ax_fam.invert_yaxis()
    
    # Discrete colorbar
    cbar = fig.colorbar(im, ax=ax_heat, shrink=0.15, aspect=6, pad=0.015)
    cbar.set_ticks(range(max_cn + 1))
    cbar.set_ticklabels([str(i) for i in range(max_cn + 1)])
    cbar.set_label('Copy number', fontsize=9)
    cbar.outline.set_visible(False)
    
    # Remove spines
    for a in axes:
        for sp in a.spines.values():
            sp.set_visible(False)
    
    # Title (tight to the top of the plot)
    ax_heat.set_title(
        f'Marker Gene Copy Number per EVE (n={n_rows})',
        fontsize=13, fontweight='bold', pad=40,
    )
    
    # Legend (tight below the plot)
    fam_present = sorted(set(canon_family(profiles[e].get('likely_family')) for e in marker_df.index))
    legend_handles = []
    for fam in fam_present:
        legend_handles.append(mpatches.Patch(
            facecolor=FAMILY_COLORS.get(fam, '#BBBBBB'), label=fam))
    legend_handles.append(_Line2D([0], [0], color='none', label=''))  # spacer
    for cl in unique_clusters:
        short = cl.replace('Cluster_', 'C')
        n_members = sum(1 for v in eve_cluster_map.values() if v == cl)
        legend_handles.append(mpatches.Patch(
            facecolor=cluster_cpal[cl], label=f'{short} (n={n_members})'))
    legend_handles.append(mpatches.Patch(
        facecolor='#E8E8E8', edgecolor='#CCCCCC', label='Singleton'))
    
    fig.legend(
        handles=legend_handles, loc='lower center', ncol=len(legend_handles),
        fontsize=7, frameon=False, bbox_to_anchor=(0.55, -0.005),
    )
    
    plt.subplots_adjust(top=0.97, bottom=0.03)
    plt.savefig(BASE / 'eve_marker_heatmap.png', dpi=300, bbox_inches='tight',
                pad_inches=0.15)
    plt.show()
    
    from IPython.display import FileLink
    FileLink(str(BASE / 'eve_marker_heatmap.png'))
    

# %%
if not profiles:
    print('No EVEs for marker summary.')
else:
    # ---- Marker composition per canonical EVE ----
    marker_counts = Counter()
    family_counts = Counter()
    ipr_keyword_counts = Counter()
    
    for eve_id, profile in profiles.items():
        for marker in profile.get('hallmark_genes', []):
            marker_counts[marker] += 1
        for fam in profile.get('marker_family_hits', []):
            family_counts[fam] += 1
        for kw in profile.get('interproscan_keyword_hits', []):
            short = kw[:60] + '...' if len(kw) > 60 else kw
            ipr_keyword_counts[short] += 1
    
    print('Top 15 hallmark markers:')
    for marker, n in marker_counts.most_common(15):
        print(f'  {marker:<30s} {n:>3d} EVEs')
    
    print(f'\nMarker family distribution:')
    for fam, n in family_counts.most_common():
        print(f'  {fam:<15s} {n:>3d} EVEs')
    
    # Jelly roll summary
    if jelly_roll_map:
        print(f'\nJelly roll capsid proteins: {len(jelly_roll_map)}')
        jr_types = Counter(v['type'] for v in jelly_roll_map.values())
        for jt, n in jr_types.most_common():
            print(f'  {jt}: {n}')
    else:
        print('\nNo jelly roll capsid proteins detected in this run.')
    
    # Functional group color mapping for InterProScan keywords
    def keyword_color(kw):
        kw_lower = kw.lower()
        if any(w in kw_lower for w in ['capsid', 'jelly', 'coat']):
            return '#CC3311'    # red -- capsid / structural
        if any(w in kw_lower for w in ['polymerase', 'replicase', 'transcriptas']):
            return '#0077BB'    # blue -- replication
        if any(w in kw_lower for w in ['protease', 'peptidase', 'cleavage']):
            return '#EE7733'    # orange -- protease
        if any(w in kw_lower for w in ['helicase', 'atpase', 'topoisomerase']):
            return '#009988'    # teal -- helicase / NTPase
        if any(w in kw_lower for w in ['kinase', 'phospho', 'ligase', 'transferase']):
            return '#AA3377'    # wine -- enzyme
        return '#888888'        # gray -- other
    
    n_total = len(profiles)
    top_kw = ipr_keyword_counts.most_common(15)
    if top_kw:
        fig, ax = plt.subplots(figsize=(6, 4))
        labels, vals = zip(*top_kw)
        y_pos = np.arange(len(labels))
        bar_colors = [keyword_color(l) for l in labels]
    
        bars = ax.barh(y_pos, vals, color=bar_colors, edgecolor='white', linewidth=0.5)
        ax.set_yticks(y_pos)
        ax.set_yticklabels(labels, fontsize=8)
        ax.invert_yaxis()
    
        # Percentage annotations
        for bar, val in zip(bars, vals):
            pct = safe_ratio(val, n_total) * 100
            ax.text(bar.get_width() + 0.5, bar.get_y() + bar.get_height() / 2,
                    f'{val} ({pct:.0f}%)', va='center', fontsize=8, color='#444444')
    
        ax.set_xlabel(f'Number of EVEs with keyword hit (n={n_total} total)')
        ax.set_title('Top InterProScan Keyword Hits Across EVEs')
        finalize_axes(ax)
    
        # Functional group legend
        func_legend = [
            mpatches.Patch(facecolor='#CC3311', label='Capsid / structural'),
            mpatches.Patch(facecolor='#0077BB', label='Replication'),
            mpatches.Patch(facecolor='#EE7733', label='Protease'),
            mpatches.Patch(facecolor='#009988', label='Helicase / NTPase'),
            mpatches.Patch(facecolor='#AA3377', label='Enzyme'),
            mpatches.Patch(facecolor='#888888', label='Other'),
        ]
        ax.legend(handles=func_legend, loc='lower right', fontsize=8, title='Functional group',
                  title_fontsize=9)
    
        plt.tight_layout()
        plt.savefig(BASE / 'eve_interproscan_keywords.png', dpi=300)
        plt.show()
    else:
        print('No InterProScan keyword hits found.')
    
    from IPython.display import FileLink
    FileLink(str(BASE / 'eve_interproscan_keywords.png'))
